WARNING 03-07 14:35:50 _custom_ops.py:19] Failed to import from vllm._C with ModuleNotFoundError("No module named 'vllm._C'")
Namespace(backend='openai', host='localhost', port=63313, endpoint='/v1/completions', dataset=None, dataset_name='sharegpt', dataset_path='/gpfs/scratch/bsc98/bsc098069/llm_benchmarking/data/ShareGPT_V3_unfiltered_cleaned_split.json', model='/gpfs/scratch/bsc98/bsc098069/llm_benchmarking/models/opt/opt-2.7b', tokenizer=None, best_of=1, use_beam_search=False, num_prompts=2000, logprobs=None, request_rate=inf, seed=0, trust_remote_code=False, disable_tqdm=True, save_result=True, metadata=None, result_dir='benchmarks/definitive_results/replication/overall_metrics/opt-2.7b/_128__1', result_filename=None, ignore_eos=False, percentile_metrics='ttft,tpot,itl', metric_percentiles='99', launch_server=True, server_args='--disable-log-requests --model=/gpfs/scratch/bsc98/bsc098069/llm_benchmarking/models/opt/opt-2.7b --max-model-len=2048 --max-num-seqs=128', multiple_servers=1, launch_server_with_nsight=False, disable_log_stats=False, sonnet_input_len=550, sonnet_output_len=150, sonnet_prefix_len=200, sharegpt_output_len=None, random_input_len=1024, random_output_len=128, random_range_ratio=1.0, random_prefix_len=0, hf_subset=None, hf_split=None, hf_output_len=None, include_nvtx_regions=False, use_mps=False)
Servers started
